export const randomUtils = {
  getRandomLikes: () => Math.floor(Math.random() * (100000 - 1 + 1)) + 10,
  getRandomInteractions: () => Math.floor(Math.random() * (5000 - 1 + 1)) + 1,
  getRandomPage: () => Math.floor(Math.random() * 5) + 1,
  getRandomBoolean: () => Math.random() < 0.5,
  getRandomFollowers: () =>
    Math.floor(Math.random() * (2000000 - 500 + 1)) + 500,
  getRandomTime: () => {
    const minutesInHour = 60
    const minutesInDay = minutesInHour * 24
    const minutesInWeek = minutesInDay * 7
    const randomCategory = Math.random()
    let randomMinutes
    if (randomCategory < 0.33) {
      randomMinutes =
        Math.floor(Math.random() * (23 * minutesInHour)) + minutesInHour
      return `${Math.round(randomMinutes / minutesInHour)} hours`
    } else if (randomCategory < 0.66) {
      randomMinutes =
        Math.floor(Math.random() * (6 * minutesInDay)) + minutesInDay
      return `${Math.round(randomMinutes / minutesInDay)} days`
    } else {
      randomMinutes =
        Math.floor(Math.random() * (3 * minutesInWeek)) + minutesInWeek
      return `${Math.round(randomMinutes / minutesInWeek)} weeks`
    }
  },
  getRandomCapital: () => {
    const capitals = [
      'Washington D.C',
      'Beijing',
      'Moscow',
      'Berlin',
      'Paris',
      'London',
      'Tokyo',
      'New Delhi',
      'Brasilia',
      'Ottawa',
      'Canberra',
      'Rome',
      'Madrid',
      'Seoul',
      'Mexico City',
      'Jakarta',
      'Riyadh',
      'Buenos Aires',
      'Cairo',
      'Pretoria'
    ]
    const randomIndex = Math.floor(Math.random() * capitals.length)
    return capitals[randomIndex]
  },
  getRandomDescription: () => {
    const descriptions = [
      'Frontend Developer | React & Next.js | Crafting Sleek Applications',
      'Social Media Expert | Strategy & Engagement | Growing Brand Presence',
      'Pro Gamer | FPS & Strategy | Turning Skill into Victories',
      'Travel Blogger | Adventure & Culture | Exploring the World',
      'E-commerce Specialist | SEO & Ads | Boosting Product Reach',
      'Live Streamer | Gaming & Lifestyle | Connecting Live with Fans',
      'Data Analyst | Python & SQL | Turning Data into Insights',
      'Fashion Influencer | Style & Wellness | Inspiring Daily Confidence',
      'IT Support | Network & Security | Keeping Systems Running',
      'Content Creator | Vlogs & Lifestyle | Sharing Moments with You',
      'Product Designer | Figma & UX | Crafting User-Friendly Apps',
      'Digital Nomad | Marketing Anywhere | Growing Brands Worldwide',
      'Digital Artist | Streams & Animation | Creativity on Every Screen',
      'Mobile Developer | Swift & Kotlin | Building Mobile Solutions',
      'Gaming YouTuber | Reviews & Playthroughs | Honest Game Insights',
      'Full-Stack Developer | MERN Stack | Ideas to Reality',
      'Photographer | Nature & Landscapes | Capturing the World',
      'UX Researcher | Testing & Insights | Improving User Experiences',
      'Freelance Writer | Copy & Storytelling | Words that Connect',
      'Cybersecurity Specialist | Defense & Protection | Keeping Data Safe',
      'Travel Photographer | Local & Culture | Capturing Unique Places',
      'Virtual Host | Events & Networking | Unforgettable Online Events',
      'VR Developer | Unity & Worlds | Creating Immersive Spaces',
      'Music Streamer | Covers & Originals | Live Music Experiences',
      'SEO Consultant | Strategy & Growth | Driving Engagement with Precision',
      'AI Researcher | Machine Learning | Innovation for Tomorrow',
      'Outdoor Enthusiast | Hiking & Skills | Embracing Nature’s Challenges',
      'Digital Marketer | PPC & Email | Boosting Targeted Campaigns',
      'Voice Actor | Characters & Narration | Stories Brought to Life',
      'Nonprofit Advocate | Outreach & Change | Meaningful Community Work',
      'Frontend Engineer | JavaScript & Responsive | Interactive Designs',
      'Esports Host | Commentary & Analysis | Insightful Live Coverage',
      'SaaS Sales | B2B & Solutions | Client-Centered Growth',
      'Videographer | Adventure & Travel | Capturing Scenic Thrill',
      'Podcast Host | Topics & Trends | Fresh Perspectives Shared',
      'Data Scientist | AI & Models | Data for Actionable Growth',
      'Game Developer | C++ & Worlds | Immersive Gaming Experiences',
      'Wellness Coach | Fitness & Mindfulness | Helping Others Thrive',
      'Blockchain Developer | DeFi & Smart Contracts | Future of Finance',
      'Lifestyle YouTuber | DIY & Ideas | Practical Inspiration',
      'Backend Developer | APIs & Architecture | Robust Infrastructures',
      'Fitness Influencer | Workouts & Motivation | Inspiring Strength',
      'Financial Analyst | Trends & Forecasting | Data-Driven Strategy'
    ]       
    const randomIndex = Math.floor(Math.random() * descriptions.length)
    return descriptions[randomIndex]
  },
  getRandomHashtag: () => {
    const popularHashtags = [
      'love',
      'instagood',
      'fashion',
      'photooftheday',
      'beautiful',
      'art',
      'photography',
      'happy',
      'picoftheday',
      'follow',
      'nature',
      'like4like',
      'travel',
      'instagram',
      'style',
      'repost',
      'summer',
      'instadaily',
      'selfie',
      'me',
      'friends',
      'fitness',
      'food',
      'fun',
      'beauty',
      'life',
      'amazing',
      'cool',
      'smile',
      'family',
      'music',
      'ootd',
      'followme',
      'bestoftheday',
      'sunset',
      'makeup',
      'lifestyle',
      'sky',
      'beach',
      'f4f',
      'photo',
      'ootn',
      'sun',
      'model',
      'workout',
      'wedding',
      'dog',
      'girl',
      'travelgram',
      'cute',
      'amor',
      'felicidad',
      'moda',
      'fotodeldia',
      'arte',
      'fotografia',
      'paisaje',
      'like',
      'familia',
      'viaje',
      'belleza',
      'salud',
      'fiesta',
      'musica',
      'amistad',
      'sonrisa',
      'autoestima',
      'naturaleza',
      'perro',
      'gato',
      'instamoment',
      'ciudad',
      'cultura',
      'deporte',
      'comida',
      'vida',
      'trabajo',
      'frases',
      'motivacion',
      'éxito',
      'celebracion',
      'verano',
      'playa',
      'sol',
      'cielo',
      'inspiracion',
      'emprendedores',
      'musicos',
      'cine',
      'tecnologia',
      'aventura',
      'familiafeliz',
      'ocio',
      'sueños',
      'historias',
      'fotografiaurbana',
      'amorpropio',
      'instachile',
      'mexico',
      'colombia'
    ]
    return popularHashtags[Math.floor(Math.random() * popularHashtags.length)]
  }
}
