export const randomUtils = {
  getRandomLikes: () => Math.floor(Math.random() * (100000 - 1 + 1)) + 10,
  getRandomInteractions: () => Math.floor(Math.random() * (5000 - 1 + 1)) + 1,
  getRandomPage: () => Math.floor(Math.random() * 5) + 1,
  getRandomBoolean: () => Math.random() < 0.5,
  getRandomFollowers: () =>
    Math.floor(Math.random() * (2000000 - 500 + 1)) + 500,
  getRandomTime: () => {
    const minutesInHour = 60
    const minutesInDay = minutesInHour * 24
    const minutesInWeek = minutesInDay * 7
    const randomCategory = Math.random()
    let randomMinutes
    if (randomCategory < 0.33) {
      randomMinutes =
        Math.floor(Math.random() * (23 * minutesInHour)) + minutesInHour
      return `${Math.round(randomMinutes / minutesInHour)} hours`
    } else if (randomCategory < 0.66) {
      randomMinutes =
        Math.floor(Math.random() * (6 * minutesInDay)) + minutesInDay
      return `${Math.round(randomMinutes / minutesInDay)} days`
    } else {
      randomMinutes =
        Math.floor(Math.random() * (3 * minutesInWeek)) + minutesInWeek
      return `${Math.round(randomMinutes / minutesInWeek)} weeks`
    }
  },
  getRandomCapital: () => {
    const capitals = [
      'Washington D.C',
      'Beijing',
      'Moscow',
      'Berlin',
      'Paris',
      'London',
      'Tokyo',
      'New Delhi',
      'Brasilia',
      'Ottawa',
      'Canberra',
      'Rome',
      'Madrid',
      'Seoul',
      'Mexico City',
      'Jakarta',
      'Riyadh',
      'Buenos Aires',
      'Cairo',
      'Pretoria'
    ]
    const randomIndex = Math.floor(Math.random() * capitals.length)
    return capitals[randomIndex]
  },
  getRandomProfesion: () => {
    const profesiones = [
      'Frontend Developer',
      'Social Media Expert',
      'Pro Gamer',
      'Travel Blogger',
      'E-commerce Specialist',
      'Live Streamer',
      'Data Analyst',
      'Fashion Influencer',
      'IT Support',
      'Content Creator',
      'Product Designer',
      'Digital Nomad',
      'Digital Artist',
      'Mobile Developer',
      'Gaming YouTuber',
      'Full-Stack Developer',
      'Photographer',
      'UX Researcher',
      'Freelance Writer',
      'Cybersecurity Specialist',
      'Travel Photographer',
      'Virtual Host',
      'VR Developer',
      'Music Streamer',
      'SEO Consultant',
      'AI Researcher',
      'Outdoor Enthusiast',
      'Digital Marketer',
      'Voice Actor',
      'Nonprofit Advocate',
      'Frontend Engineer',
      'Esports Host',
      'SaaS Sales',
      'Videographer',
      'Podcast Host',
      'Data Scientist',
      'Game Developer',
      'Wellness Coach',
      'Blockchain Developer',
      'Lifestyle YouTuber',
      'Backend Developer',
      'Fitness Influencer',
      'Financial Analyst'
    ]
    return profesiones[Math.floor(Math.random() * profesiones.length)]
  },
  getRandomIntereses: () => {
    const intereses = [
      'React & Next.js',
      'Strategy & Engagement',
      'FPS & Strategy',
      'Adventure & Culture',
      'SEO & Ads',
      'Gaming & Lifestyle',
      'Python & SQL',
      'Style & Wellness',
      'Network & Security',
      'Vlogs & Lifestyle',
      'Figma & UX',
      'Marketing Anywhere',
      'Streams & Animation',
      'Swift & Kotlin',
      'Reviews & Playthroughs',
      'MERN Stack',
      'Nature & Landscapes',
      'Testing & Insights',
      'Copy & Storytelling',
      'Defense & Protection',
      'Local & Culture',
      'Events & Networking',
      'Unity & Worlds',
      'Covers & Originals',
      'Strategy & Growth',
      'Machine Learning',
      'Hiking & Skills',
      'PPC & Email',
      'Characters & Narration',
      'Outreach & Change',
      'JavaScript & Responsive',
      'Commentary & Analysis',
      'B2B & Solutions',
      'Adventure & Travel',
      'Topics & Trends',
      'AI & Models',
      'C++ & Worlds',
      'Fitness & Mindfulness',
      'DeFi & Smart Contracts',
      'DIY & Ideas',
      'APIs & Architecture',
      'Workouts & Motivation',
      'Trends & Forecasting'
    ]
    return intereses[Math.floor(Math.random() * intereses.length)]
  },
  getRandomSlogan: () => {
    const slogans = [
      'Crafting Sleek Applications',
      'Growing Brand Presence',
      'Turning Skill into Victories',
      'Exploring the World',
      'Boosting Product Reach',
      'Connecting Live with Fans',
      'Turning Data into Insights',
      'Inspiring Daily Confidence',
      'Keeping Systems Running',
      'Sharing Moments with You',
      'Crafting User-Friendly Apps',
      'Growing Brands Worldwide',
      'Creativity on Every Screen',
      'Building Mobile Solutions',
      'Honest Game Insights',
      'Ideas to Reality',
      'Capturing the World',
      'Improving User Experiences',
      'Words that Connect',
      'Keeping Data Safe',
      'Capturing Unique Places',
      'Unforgettable Online Events',
      'Creating Immersive Spaces',
      'Live Music Experiences',
      'Driving Engagement with Precision',
      'Innovation for Tomorrow',
      'Embracing Nature’s Challenges',
      'Boosting Targeted Campaigns',
      'Stories Brought to Life',
      'Meaningful Community Work',
      'Interactive Designs',
      'Insightful Live Coverage',
      'Client-Centered Growth',
      'Capturing Scenic Thrill',
      'Fresh Perspectives Shared',
      'Data for Actionable Growth',
      'Immersive Gaming Experiences',
      'Helping Others Thrive',
      'Future of Finance',
      'Practical Inspiration',
      'Robust Infrastructures',
      'Inspiring Strength',
      'Data-Driven Strategy'
    ]
    return slogans[Math.floor(Math.random() * slogans.length)]
  },
  getRandomHashtag: () => {
    const popularHashtags = [
      'love',
      'instagood',
      'fashion',
      'photooftheday',
      'beautiful',
      'art',
      'photography',
      'happy',
      'picoftheday',
      'follow',
      'nature',
      'like4like',
      'travel',
      'instagram',
      'style',
      'repost',
      'summer',
      'instadaily',
      'selfie',
      'me',
      'friends',
      'fitness',
      'food',
      'fun',
      'beauty',
      'life',
      'amazing',
      'cool',
      'smile',
      'family',
      'music',
      'ootd',
      'followme',
      'bestoftheday',
      'sunset',
      'makeup',
      'lifestyle',
      'sky',
      'beach',
      'f4f',
      'photo',
      'ootn',
      'sun',
      'model',
      'workout',
      'wedding',
      'dog',
      'girl',
      'travelgram',
      'cute',
      'amor',
      'felicidad',
      'moda',
      'fotodeldia',
      'arte',
      'fotografia',
      'paisaje',
      'like',
      'familia',
      'viaje',
      'belleza',
      'salud',
      'fiesta',
      'musica',
      'amistad',
      'sonrisa',
      'autoestima',
      'naturaleza',
      'perro',
      'gato',
      'instamoment',
      'ciudad',
      'cultura',
      'deporte',
      'comida',
      'vida',
      'trabajo',
      'frases',
      'motivacion',
      'éxito',
      'celebracion',
      'verano',
      'playa',
      'sol',
      'cielo',
      'inspiracion',
      'emprendedores',
      'musicos',
      'cine',
      'tecnologia',
      'aventura',
      'familiafeliz',
      'ocio',
      'sueños',
      'historias',
      'fotografiaurbana',
      'amorpropio',
      'instachile',
      'mexico',
      'colombia'
    ]
    return popularHashtags[Math.floor(Math.random() * popularHashtags.length)]
  },
  getRandomImageDescription: () => {
    const intros = [
      'Check out this amazing capture.',
      "Here's a snapshot of inspiration.",
      'A moment worth sharing.',
      'A visual story of the day.',
      'Another great memory.',
      'Bringing you a glimpse of beauty.',
      'Captured just for you.',
      'A scene that speaks for itself.',
      'A perfect moment to share.',
      'A picture worth a thousand words.'
    ];
    const hashtags = Array.from(
      { length: 5 },
      () => `#${randomUtils.getRandomHashtag()}`
    ).join(' ');
    return `${intros[Math.floor(Math.random() * intros.length)]}\n${hashtags}`;
  }  
}
